export const APP_VERSION = '2.14.0';

// Historial de versiones
export const VERSION_HISTORY = {
  '2.14.0': 'Optimization: Sistema alertas optimizado - Usuario actual, EPPs del panel, recurrencia 10min, UI compacta',
  '2.13.0': 'Fix: Correcciones sistema alertas - CORS, email supervisor, push parsing, leyendas específicas, auto-solicitud push',
  '2.12.0': 'Feature: Sistema de alertas multicanal - Push notifications, Email y SMS a supervisores',
  '2.11.0': 'Feature: Sistema de alertas SMS en tiempo real - Notificaciones cuando no se detectan EPPs críticos',
  '2.10.1': 'Fix: Desactivar temporalmente detección de objetos en tiempo real hasta completar desarrollo',
  '2.10.0': 'Feature: Detección EPP en tiempo real con Rekognition - motion detection + análisis cada 10s',
  '2.9.8': 'Fix: Simplificación de inicialización - delay de 500ms para asegurar autenticación',
  '2.9.7': 'Fix crítico: Error de autenticación al cargar datos - inicialización después de login',
  '2.9.6': 'Refactor: Eliminado modo avanzado - solo asistente guiado para simplificar UX',
  '2.9.5': 'Fix: Detección rol admin + reset password con contraseña temporal',
  '2.9.4': 'Feature: Informe completo en admin con ImageComparison (tabla EPP + imágenes lado a lado)',
  '2.9.3': 'Feature: Historial usuario con paginación + modal informe completo (UI idéntica a Historial)',
  '2.9.2': 'Feature: Gráficos de actividad temporal (últimos 30 días) con recharts',
  '2.9.1': 'Feature: Historial por usuario + usuarios activos + corrección conteo usuarios',
  '2.9.0': 'Feature: Panel de administración con estadísticas y gestión de usuarios',
  '2.8.37': 'Fix: Historial ordenado por timestamp descendente + eliminación de duplicados',
  '2.8.36': 'Performance: Contador global optimizado - DynamoDB Scan en lugar de S3 ListObjects (~100ms vs ~2s)',
  '2.8.35': 'Performance: Lazy loading historial + paginación (10 items) + botón "Cargar más"',
  '2.8.34': 'UX: Eliminar toast flotante redundante + texto "fueron incluidas" en lugar de "evaluadas completamente"',
  '2.8.33': 'UX: Botón análisis unificado en modo guiado con estados de progreso',
  '2.8.32': 'UX: Botón análisis unificado con estados de progreso (subiendo/analizando/generando IA/completado)',
  '2.8.31': 'Feature: Diferenciar colores en tabla EPP (verde ≥75%, amarillo 40-74%, rojo <40%)',
  '2.8.30': 'Debug: Agregar logs al crear analysisResult',
  '2.8.29': 'Debug: Agregar logs para diagnosticar cálculo de cumplientes',
  '2.8.28': 'Fix: Calcular cumplientes con EPPs seleccionados en lugar de todos los EPPs',
  '2.8.27': 'Fix: Traducciones de código de verificación en Cognito a español',
  '2.8.26': 'Fix: Usar API Gateway correcta (kmekzxexq5) para solicitar URL presignada',
  '2.8.25': 'Fix: Generar URL presignada para análisis antiguos al generar PDF',
  '2.8.24': 'Fix: Usar imagePresignedUrl de Lambda para cargar imágenes en PDF (solución definitiva)',
  '2.8.23': 'Fix: Carga de imágenes en PDF usando patrón img+canvas (mejor práctica AWS)',
  '2.8.22': 'Fix: Carga de imágenes en PDF con mode cors para URLs presignadas de S3',
  '2.8.21': 'Feature: Botones Reportar Error y Feedback disponibles para TODOS los tipos de detección',
  '2.8.20': 'Fix: Badges de EPPs en historial solo se muestran para análisis de tipo ppe_detection',
  '2.8.19': 'Feature: Email de feedback incluye nombre de usuario, ID y tipo de análisis',
  '2.8.18': 'Fix crítico: Guardado en DynamoDB para TODOS los tipos en modo guiado',
  '2.8.17': 'Debug: Logs de diagnóstico para guardado en DynamoDB',
  '2.8.16': 'Fix crítico: TODOS los tipos de análisis se guardan en historial (EPP/rostros/objetos/texto)',
  '2.8.15': 'Feature: analysisId visible en resumen y historial de TODOS los tipos de análisis',
  '2.8.14': 'Fix: EPP se guarda 1 sola vez con resumen IA, evita sobrescritura',
  '2.8.13': 'Fix: Historial ahora guarda TODOS los tipos de análisis (objetos/rostros/texto/EPP)',
  '2.8.12': 'Fix: Detección facial ahora muestra edad, género, emociones y atributos completos',
  '2.8.11': 'Fix: Lambda genera presignedUrl para TODOS los tipos de detección (objetos/rostros/texto)',
  '2.8.10': 'Fix: Detección de objetos/rostros/texto funcional (manejo de respuestas sin presignedUrl)',
  '2.8.9': 'Fix: ContactModal agrega campo subject al payload para compatibilidad con Lambda',
  '2.8.8': 'PDF sin emojis + viñetas justificadas + ContactModal rediseñado con desplegable',
  '2.8.7': 'Formulario de contacto unificado con autocompletado de analysisId al reportar errores',
  '2.8.6': 'Fix: Dashboard análisis recientes ordenados + PDF cumplimiento correcto + párrafos justificados',
  '2.8.5': 'Fix: Cumplimiento correcto en historial/dashboard + ordenamiento por timestamp',
  '2.8.4': 'Optimización: Guardado único en DynamoDB con resumen IA completo (evita sobrescritura)',
  '2.8.3': 'Fix: MinConfidence ahora se guarda correctamente en DynamoDB (visible en historial)',
  '2.8.2': 'Fix: 4 correcciones críticas (analysisId al inicio resumen, PDF FOOT_COVER completo, analysisId duplicado eliminado, Lambda Bedrock EPPs)',
  '2.8.1': 'Fix: 10 correcciones (badges colores EPPs, analysisId visible, PDF centrado/justificado, resumen IA completo, historial mejorado)',
  '2.8.0': 'Mejoras UX: Badges colores EPP (verde/amarillo/rojo), analysisId UUID visible, formulario contacto autocompletado',
  '2.7.7': 'Fix definitivo: Verificación espacial correcta (centro del EPP dentro de persona)',
  '2.7.6': 'Fix crítico: Eliminar lógica IoU - restaurar comportamiento anterior que funcionaba',
  '2.7.5': 'Fix: Priorizar labels con instancias (Shoe sobre Footwear)',
  '2.7.4': 'Fix: Búsqueda exacta de labels (Shoe, Footwear, Glasses)',
  '2.7.3': 'Fix crítico: Detección espacial IoU - EPPs híbridos solo se agregan a personas con solapamiento',
  '2.7.2': 'Fix: Mapeo LEFT_FOOT/RIGHT_FOOT para mostrar calzado en tabla',
  '2.7.1': 'Fix: Crear BodyParts faltantes para EPPs detectados por labels (calzado ahora visible en tabla)',
  '2.7.0': 'Feature: Detección híbrida EPPs (nativa + labels) - gafas, calzado, orejeras detectables',
  '2.6.18': 'Fix definitivo: Lambda usa MinConfidence 50 fijo, todos los EPPs ≥50% llegan al frontend',
  '2.6.17': 'Fix crítico: Lambda siempre detecta con 50% mínimo, umbral usuario solo afecta estado',
  '2.6.16': 'Fix crítico: Anotaciones visuales muestran TODOS los EPPs detectados (boxes en imagen)',
  '2.6.15': 'Fix crítico: Tabla muestra TODOS los EPPs detectados, umbral solo determina Cumple/No cumple',
  '2.6.14': 'Mejora: Mostrar EPPs bajo umbral + diferenciar "No detectado" vs "Bajo umbral"',
  '2.6.13': 'Mejora: PDF rediseñado con tabla detallada de evaluabilidad y diseño moderno',
  '2.6.12': 'Fix: Tabla mejorada visible en historial con selectedEPPs correctos',
  '2.6.11': 'Mejora: Tabla detallada por persona con evaluabilidad + explicación EPP vs parte del cuerpo',
  '2.6.10': 'Fix: Logo de CoironTech restaurado en PDF usando fetch desde /public',
  '2.6.9': 'Fix: CORS S3 configurado correctamente para epi.coirontech.com + logo deshabilitado',
  '2.6.8': 'Fix: Carga de imagen en PDF usando fetch en lugar de canvas (evita CORS)',
  '2.6.7': 'Fix: Mejorada carga de imágenes en PDF con timeout y mejor manejo de errores',
  '2.6.6': 'Fix: Imagen en PDF ahora mantiene aspect ratio correcto (no se estira)',
  '2.6.5': 'Fix crítico: Tabla EPP ahora muestra todas las detecciones sin filtros restrictivos',
  '2.6.4': 'Fix crítico: Tabla EPP visible inmediatamente después del análisis, PDF con imagen única',
  '2.6.3': 'Fix: Tabla EPP visible después de análisis, imagen única en PDF',
  '2.6.2': 'Fix: Imágenes en PDF funcionando - acceso público S3 output',
  '2.6.1': 'Fix: Footer PDF sin teléfono, EPPs en informe historial, mejor carga imágenes',
  '2.6.0': 'PDF completo: logo, imágenes comparativas, footer corporativo',
  '2.5.9': 'Correcciones UX: EPPs en historial, timing resultados, feedback reposicionado',
  '2.5.8': 'EPPs seleccionados en historial/PDF + botón reportar errores',
  '2.5.7': 'Evaluación parcial: persona evaluable si tiene AL MENOS UNA parte visible',
  '2.5.6': 'Filtrado dinámico correcto: evalúa según EPPs requeridos',
  '2.5.5': 'Filtrado ESTRICTO: solo personas con FOOT visible (cuerpo completo)',
  '2.5.4': 'Filtrado completo: Lambda Bedrock + tabla detalles EPP',
  '2.5.3': 'Filtrado inteligente de personas: solo evalúa personas con partes visibles',
  '2.5.2': 'Modo avanzado deshabilitado temporalmente (inconsistencias en historial)',
  '2.5.1': 'Correcciones críticas: modo avanzado, evaluación inteligente EPP, modal feedback',
  '2.5.0': 'Formulario de contacto con tabs + FAQ corregido',
  '2.4.3': 'Sistema de feedback post-análisis',
  '2.4.2': 'Sección FAQ con 12 preguntas frecuentes',
  '2.4.1': 'Validación de seguridad en Lambdas + Rate limiting',
  '2.4.0': 'Listas geográficas en cascada para perfil de usuario',
  '2.3.3': 'Correcciones críticas: PDFs únicos, eliminar análisis, deshabilitar PDF no-EPP',
  '2.3.2': 'Edición de perfil desde menú usuario',
  '2.3.1': 'Correcciones API Gateway y permisos IAM',
  '2.3.0': 'Resúmenes IA con Claude 3 Haiku y exportación PDF',
  '2.2.0': 'Integración completa con AWS (Cognito, DynamoDB)',
  '2.1.1': 'Optimizaciones de UX y flujo del asistente',
  '2.1.0': 'Análisis de video y detección en tiempo real',
  '2.0.0': 'Rediseño completo con branding CoironTech',
  '1.1.0': 'Multi-detección (rostros, texto, objetos)',
  '1.0.0': 'Release inicial'
};

// Fecha de última actualización
export const LAST_UPDATE = '2025-11-20';
